import time

import pytest

from pageObjects.LoanProposal import LoanProposal
from pageObjects.LoginPage import LoginPage
from pageObjects.Promoters import Promoters
from utilities.readProperties import ReadConfig
from utilities.customLogger import LogGen


# def random_generator(size=8, chars=string.ascii_lowercase + string.digits):
#     return ''.join(random.choice(chars) for x in range(size))
#
#
# def generate_random_number(length=9):
#     return int(''.join([str(random.randint(6, 9))]) + ''.join([str(random.randint(0, 9)) for _ in range(length)]))


class Test_loan_proposal:
    baseURL = ReadConfig.getApplicationURL()
    username = ReadConfig.getUsername()
    password = ReadConfig.getPassword()
    path = ".//TestData/Bank statement.pdf"
    logger = LogGen.loggen()

    @pytest.mark.regression
    # @pytest.mark.sanity
    def test_new_entity_login(self, setup):
        self.logger.info("************* Test_loan_proposal **********")
        self.driver = setup
        self.driver.get(self.baseURL)
        self.driver.maximize_window()
        time.sleep(5)
        self.lp = LoginPage(self.driver)
        self.lp.setUserName(self.username)
        time.sleep(3)
        self.lp.setPassword(self.password)
        self.lp.clickLogin()
        time.sleep(5)
        self.logger.info("************* Login successful **********")
        time.sleep(5)
        self.pg = Promoters(self.driver)
        self.pg.clickonanyentity()
        self.driver.refresh()
        time.sleep(5)
        self.logger.info("************* Clicked on Loan Proposal tab **********")
        self.lpp = LoanProposal(self.driver)
        self.lpp.clickLoanProposaltab()
        time.sleep(5)
        self.lpp.clickaddNewProposal()
        time.sleep(5)
        self.lpp.clickLoanProduct()
        time.sleep(5)
        self.lpp.selectLoanProduct()
        time.sleep(5)
        self.lpp.clickLender()
        time.sleep(5)
        self.lpp.selectLender()
        time.sleep(5)
        self.lpp.setROI("4")
        self.lpp.setLoanAmount("90000")
        time.sleep(5)
        self.lpp.setLTV("56")
        self.lpp.setTenure("5")
        self.lpp.clickTenureUnit()
        self.lpp.selectTenureUnit()
        self.lpp.setProposedLoanAmount("22")
        self.lpp.setProposedCommercialOffered("22")
        self.lpp.clickRepaymentType()
        self.lpp.selectRepaymentType()
        self.lpp.clickCategory()
        self.lpp.selectCategory()
        self.lpp.clickAgreementType()
        self.lpp.selectAgreementType()
        self.lpp.clickCommission()
        self.lpp.selectCommission()
        self.lpp.setGlobalMargin("3")
        self.lpp.setPurposeOfLoan("Sales")
        time.sleep(5)
        self.lpp.clickSubmitLoanProposal()
        time.sleep(5)
        self.driver.refresh()
        time.sleep(5)
        self.lpp.clickLoanProposaltab()
        time.sleep(5)
        self.lpp.clicklink()
        time.sleep(5)
        self.lpp.clickANPS()
        time.sleep(5)
        self.lpp.clickfirstproduct()
        self.lpp.selectfirstproduct()
        time.sleep(3)
        self.lpp.clickProductBrand()
        time.sleep(3)
        self.lpp.selectProductBrand()
        time.sleep(3)
        self.lpp.clickOperator()
        time.sleep(3)
        self.lpp.selectOperator()
        time.sleep(3)
        self.lpp.setTenureMargin("5")
        time.sleep(3)
        self.lpp.clickunit()
        time.sleep(3)
        self.lpp.selectunit()
        time.sleep(3)
        self.lpp.clickoperator()
        time.sleep(3)
        self.lpp.selectoperator()
        time.sleep(3)
        self.lpp.setPriceRs("5000")
        time.sleep(3)
        self.lpp.clickMarginUnit()
        time.sleep(3)
        self.lpp.selectMarginUnit()
        time.sleep(3)
        self.lpp.setMargin("7")
        time.sleep(3)
        self.lpp.clickSubmit()
        time.sleep(5)
        self.driver.refresh()
        time.sleep(5)
        self.lpp.clickLoanProposaltab()
        time.sleep(5)
        self.lpp.clicklink()
        time.sleep(5)
        self.lpp.clickNPA()
        time.sleep(3)
        self.lpp.setFLDGvalue("5")
        time.sleep(3)
        self.lpp.setNoOFPDCsCollected("3")
        self.lpp.setBuyBackArrangements("6")
        time.sleep(3)
        self.lpp.setPlatformPeriod("8")
        self.lpp.clickSubmitPAL()
        time.sleep(3)
        self.logger.info("************* Loan Proposal created **********")
        # self.lpp.clickDocJKDDQuestionnaire("D://User/Rajeshwari/EntityOnboarding/Statements/Bank statement.pdf")
        self.driver.close()
